name: 'Runtime Update YAML'
description: 'Update YAML content based on the github input'
author: 'pratap.patil@zebra.com'
inputs:
  data: # change this
    required: true
    description: 'input description here'
runs:
  using: 'node16'
  main: 'dist/index.js'
